#!/usr/bin/env bash
##
##  So many years of fooling around...
##
##


[ -e $f ] && rm -rf $HISTFILE


function dynamic_aliases {
  if sed --version >&/dev/null 2>&1
  then  # GNU sed
    rsed="sed -r"
  else  # BSD sed
    rsed="sed -E"
  fi
  if ls --version >&/dev/null 2>&1
  then  # GNU ls
    alias l='ls --color'
    alias ll='ls -lA --color'
  else  # BSD ls
    alias l='ls -G'
    alias ll='ls -GlA'
  fi
}

dynamic_aliases

for d in /etc /usr/local/etc /opt/local/etc
do
  [ -f $d/bash_completion ] && source $d/bash_completion
done



## begin prompt #######################################################

DARK="\[\e[01;34m\]"
NORM="\[\e[01;32m\]"
FADE="\[\e[01;30m\]"
REST="\[\e[00;00m\]"
HIGH="\[\e[01;33m\]"

function dir {
  pwd -P | $rsed 's/^(.{19})..+.(.{18})$/\1...\2/'  # At most 40 chars.
}

function host {
  hostname | $rsed 's/^(.{9})..+.(.{8})$/\1...\2/'  # At most 20 chars.
}

function user {
  whoami | $rsed 's/^(.{7})..+.(.{6})$/\1...\2/'    # At most 16 chars.
}

function bold {
  tput bold
}


function pretty_prompt {
  local gray='setaf 0'
  local blue='setaf 4'
  local green='setaf 2'
  local red='setaf 1'
  local -A s=( [user]=$(user) [host]=$(host) [dir]=$(dir) )
  local rfill=79
  local buff=""
  local component=""
  buff="$buff""$(tput bold)""$(tput $blue)"
  buff="$buff"": "                   ;  let "rfill-=2"
  buff="$buff""$([[ ${s[user]} = root ]] && tput $red)"
  buff="$buff""${s[user]}"           ;  let "rfill-=${#s[user]}"
  buff="$buff""$(tput $gray)"
  buff="$buff"'@'                    ;  let "rfill-=1"
  buff="$buff""$(tput $blue)"
  buff="$buff""${s[host]}"           ;  let "rfill-=${#s[host]}"
  buff="$buff""$(tput $gray)"
  buff="$buff"':'                    ;  let "rfill-=1"
  buff="$buff""$(tput $green)"
  while read -r -d/ component
  do
    buff="$buff""$(tput $green)"
    buff="$buff""$component"         ;  let "rfill-=${#component}"
    case "$?" in
      0)  buff="$buff""$(tput $gray)"
          buff="$buff"'/'            ;  let "rfill-=1" ;;
    esac
  done <<<"${s[dir]}"
  buff="$buff""$(tput $green)"
  buff="$buff""$component"           ;  let "rfill-=${#component}"
  for space in $(seq 1 $rfill)
  do
    buff="$buff"' '
  done
  buff="$buff""$(tput $gray);"
  echo "$buff"
}


export          PROMPT_COMMAND=pretty_prompt
export          PS1="$DARK:$FADE;  $REST"
export          PS2='  '

## end prompt #########################################################


##if which vimpager >&/dev/null
##then
##  export        PAGER=vimpager
##  export        MANPAGER=vimmanpager
##fi
export          EDITOR=vim
export          TEXEDIT="${EDITOR} +%d %s"
export          PATH=$PATH:/sbin/:/usr/sbin/:$HOME/bin:./bin:.
export          TZ=/usr/share/zoneinfo/America/Los_Angeles

alias           go='pushd'
alias           b='popd'
alias           h='history'
alias           r='rm -r'
alias           :x='exit'
alias           :q='exit'
alias           :e=$EDITOR

set -o vi


