#!/usr/bin/env bash

[[ ! -f $HISTFILE ]] || rm -rf "$HISTFILE"


function dynamic_aliases {
  if sed --version >&/dev/null
  then  # GNU sed
    rsed="sed -r"
  else  # BSD sed
    rsed="sed -E"
  fi
  if ls --version >&/dev/null
  then  # GNU ls
    alias l='ls --color'
    alias ll='ls -lA --color'
  else  # BSD ls
    alias l='ls -G'
    alias ll='ls -GlA'
  fi
}

dynamic_aliases

for f in {/usr/local/etc,/opt/local/etc}/profile
do [[ ! -s $f ]] || source "$f"
done

for f in /usr/local/etc/bash_completion.d/*
do [[ ! -s $f ]] || source "$f"
done


## begin prompt #######################################################

function ellipsis {
  local n=$(( 10#$1 - 3 ))
  local b=$(( $n / 2 ))
  local a=$(( $n - $b ))
  local s="$2"
  local color="${3:-}"
  if [[ ${#s} -le $1 ]]
  then
    printf '%s\n' "$s"
  else
    local i=$(( ${#s} - $b + 1 ))
    local m="$(cut -c1-$a <<<"$s")"
    local n="$(cut -c$i-${#s} <<<"$s")"
    if [[ "$color" ]]
    then
      printf '%s\n' "$m$(tput $gray)...$(tput $color)$n"
    else
      printf '%s\n' "$m$n"
    fi
  fi
}

function escape_special {
  sed -n '1 { x ;} ; 2,$ { H ; x ; s/\n/^J/ ; x ;} ; $ { x ; p ;}' | cat -t
}

function pretty_prompt {
  local gray='setaf 0'
  local blue='setaf 4'
  local green='setaf 2'
  local red='setaf 1'
  local user="$(ellipsis 16 "$(whoami)" "$blue")"
  local host="$(ellipsis 20 "$(hostname)" "$blue")"
  local dir="$(ellipsis 40 "$(pwd -P | escape_special)" "$green")"
  local buff=""
  local component=""
  buff+="$(tput bold)""$(tput $blue)"
  buff+="# "
  buff+="$([[ $user != root ]] || tput $red)"
  buff+="$user"
  buff+="$(tput $gray)"
  buff+='@'
  buff+="$(tput $blue)"
  buff+="$host"
  buff+="$(tput $gray)"
  buff+=':'
  buff+="$(tput $green)"
  while read -r -d/ component
  do
    buff+="$(tput $green)"
    buff+="$component"
    case $? in
      0) buff+="$(tput $gray)"
         buff+='/'
    esac
  done <<<"$dir"
  buff+="$(tput $green)"
  buff+="$component"
  printf '%s\n' "$buff"
}

export          PROMPT_COMMAND=pretty_prompt
export          PS1="\[\e[01;34m\]:\[\e[01;30m\];  \[\e[00;00m\]"
export          PS2='  '

## end prompt #########################################################


##if which vimpager >&/dev/null
##then
##  export        PAGER=vimpager
##  export        MANPAGER=vimmanpager
##fi
export EDITOR=vim
export TEXEDIT="${EDITOR} +%d %s"
for d in /sbin /usr/sbin "$HOME/bin" ./bin .
do [[ $PATH =~ ^(.*:)$d(:.*)?$ ]] || PATH="$PATH":"$d"
done
export PATH

alias h='history'

set -o vi
shopt -s lithist

# Load local extensions
[[ ! -d ~/.bashrc.d ]] || for f in ~/.bashrc.d/*.{sh,bash}
                          do [[ ! -s "$f" ]] || source "$f"
                          done

