set background=dark
set autoindent
set ruler
set showcmd
set incsearch
set autowriteall
set autoread
set foldminlines=1
set shiftwidth=2
set softtabstop=2
" set showtabline=2
set expandtab
set textwidth=78 wrap
set nohlsearch
set foldexpr=indent(v:lnum)
set foldmethod=expr
set printoptions=header:0

" I hate backups!
set nobackup
set nowritebackup
set noswapfile

syntax on

" begin freebsd needs
set backspace=indent,eol,start
" end freebsd needs


let g:jsx_pragma_required = 0
execute pathogen#infect()

runtime macros/justify.vim
command Just :call Justify(&tw)<CR>

filetype plugin indent on

autocmd BufRead *.hsc setlocal filetype=haskell
autocmd BufEnter *.hs compiler ghc
autocmd BufEnter *.lhs compiler ghc
let g:haddock_browser = "/Applications/Firefox.app/Contents/MacOS/firefox-bin"
let g:haddock_docdir         =  "/usr/share/doc/ghc/"
let g:haddock_indexfiledir   =  "/Users/Shared/.vim/"

autocmd BufRead *.wiki setlocal filetype=wikipedia
autocmd BufRead www.tumblr.com_textpost* setlocal filetype=mkd

function s:MkNonExDir(file, buf)
  if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
    let dir=fnamemodify(a:file, ':h')
    if !isdirectory(dir)
      call mkdir(dir, 'p')
    endif
  endif
endfunction
autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))

autocmd FileType ldif setlocal list
autocmd FileType mkd setlocal textwidth=78 wrap
autocmd FileType tex setlocal textwidth=78 wrap spell spelllang=en_us

autocmd FileType mail setlocal textwidth=64 wrap spell spelllang=en_us
autocmd BufRead mail.google.com_*_*.txt setlocal filetype=mail

" wikipedia is an annoying format
" i need to figure out some 1337 h4x for it
autocmd FileType wikipedia setlocal textwidth=78

if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
  \ if &omnifunc == "" |
  \   setlocal omnifunc=syntaxcomplete#Complete |
  \ endif
endif

" au FileType c setlocal tabstop=8 shiftwidth=8 noexpandtab
au FileType python setlocal softtabstop=4 tabstop=4 shiftwidth=4 expandtab

" annoying initial highlights removed
nohlsearch

hi SignificantSpace ctermfg=cyan cterm=underline
" Leading tabs should be highlighted.
syntax match SignificantSpace /\v^\t+/
" So should trailing whitespace.
syntax match SignificantSpace /\v\s+$/

autocmd FileType go autocmd BufWritePre <buffer> Fmt
